### ISSUE TITLE
404 Page after uploading CSV file

### ISSUE THREAD

**Issue by beshoo** [simonhamp/laravel-nova-csv-import#71] opened 2023-07-04 11:20 UTC
Dear Dev, thank you for this addon.
I installed it correctly on my localhost but after uploading it redirect me to :

http://127.0.0.1:8000/dashboard/csv-import/configure/43937a4ef0d4743f485d25156ff5eb0d.csv

which is 404 error page.

`Nova latest version , laravel 10 , `

**Comment by simonhamp** [comment] 2023-07-04 14:37
@beshoo I'm closing this issue as it seems like it may be a duplicate of #44

Please note, I cannot see the URL you shared as it is for your local dev environment

Please consult that other thread

**Closed by simonhamp** 2023-07-04 14:37 UTC
